
<div class="container">
    
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="<?= $this->url('full-app',['controller'=>'index','action'=>'index']); ?>">Home</a></li>
            <li><a href="<?= $this->url('full-app',['controller'=>'cliente','action'=>'index']); ?>">Clientes</a></li>
            <li class="active">Editar</li>
        </ol>
    </div>
    
    <div class="row">
        <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cadastrar Cliente</h3>
  </div>
  <div class="panel-body">

        <?php
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>
      </div>
</div>
    </div>
</div>