<?php

namespace Application\Entity\Repository;

/**
 * Cliente
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cliente extends \Doctrine\ORM\EntityRepository
{
}
