<?php

namespace Application\Entity\Repository;

/**
 * Estacionamento
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Estacionamento extends \Doctrine\ORM\EntityRepository
{
}
