<?php

namespace Admin\Entity\Repository;

/**
 * Cargo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cargo extends AbstractRepository
{
}
