<?php

namespace Admin\Entity\Repository;

/**
 * Funcionario
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Funcionario extends AbstractRepository
{
}
