<?php

namespace Admin\Entity\Repository;

/**
 * Login
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Login extends AbstractRepository
{
}
