<?php

namespace Admin\Entity\Repository;

/**
 * Vaga
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vaga extends AbstractRepository
{
}
