<?php

namespace Application\Entity\Repository;

/**
 * Login
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Login extends \Doctrine\ORM\EntityRepository
{
}
